[project]
name = "nicegui-playground"
version = "0.1.0"
requires-python = ">= 3.12.4"
dependencies = [
  "beautifulsoup4",
  "nicegui>=2.14.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
