version: "3.5"


networks:
  nicegui_network:
    external: true

services:
  nicegui:
    image: nicegui_template
    networks:
      - nicegui_network
    environment:
      - REDIS_OM_URL=redis://@redis:6379
    ports:
      - target: 8080
        published: 8080
        mode: host
    volumes: 
      - ./src:/app/src # copy entire app into container
    depends_on:
      - redis
  