version: "3.5"

networks:
  playground_network:
    external: true

services:
  nicegui:
    image: nicegui_template
    networks:
      - playground_network
    ports:
      - target: 8080
        published: 9080
        mode: host
    volumes: 
      - ./src:/app/src # copy entire app into container
    depends_on:
      - redis
  